version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: aampere
      POSTGRES_PASSWORD: aampere
      POSTGRES_DB: aampere
    volumes:
      - ./db/data:/var/lib/postgresql/data #for persistent storage
    ports:
      - "5433:5432"
  
  backend:
    build: ./apps/backend
    container_name: aampere-backend
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://aampere:aampere@postgres:5432/aampere
    ports:
      - "4000:4000"
  
  frontend:
    build: ./apps/frontend
    container_name: aampere-frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
