--
-- PostgreSQL database cluster dump
--

SET default_transaction_read_only = off;

SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;

--
-- Roles
--

CREATE ROLE aampere;
ALTER ROLE aampere WITH SUPERUSER INHERIT CREATEROLE CREATEDB LOGIN REPLICATION BYPASSRLS PASSWORD 'SCRAM-SHA-256$4096:ycFYrbbjf1PsSMzoFm1dlg==$kLws5rFvkAriGEH54DHESdXk2WHoHsCtJrhPMAOIVPU=:g6+OhhTxp5QVNBOZSa5Ba+4beCNczEjTcdkr7tNueEU=';

--
-- User Configurations
--








--
-- Databases
--

--
-- Database "template1" dump
--

\connect template1

--
-- PostgreSQL database dump
--

-- Dumped from database version 17.2 (Debian 17.2-1.pgdg120+1)
-- Dumped by pg_dump version 17.2 (Debian 17.2-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- PostgreSQL database dump complete
--

--
-- Database "aampere" dump
--

--
-- PostgreSQL database dump
--

-- Dumped from database version 17.2 (Debian 17.2-1.pgdg120+1)
-- Dumped by pg_dump version 17.2 (Debian 17.2-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: aampere; Type: DATABASE; Schema: -; Owner: aampere
--

CREATE DATABASE aampere WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'en_US.utf8';


ALTER DATABASE aampere OWNER TO aampere;

\connect aampere

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: uuid-ossp; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;


--
-- Name: EXTENSION "uuid-ossp"; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION "uuid-ossp" IS 'generate universally unique identifiers (UUIDs)';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: migrations; Type: TABLE; Schema: public; Owner: aampere
--

CREATE TABLE public.migrations (
    id integer NOT NULL,
    "timestamp" bigint NOT NULL,
    name character varying NOT NULL
);


ALTER TABLE public.migrations OWNER TO aampere;

--
-- Name: migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: aampere
--

CREATE SEQUENCE public.migrations_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.migrations_id_seq OWNER TO aampere;

--
-- Name: migrations_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: aampere
--

ALTER SEQUENCE public.migrations_id_seq OWNED BY public.migrations.id;


--
-- Name: users; Type: TABLE; Schema: public; Owner: aampere
--

CREATE TABLE public.users (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    username character varying NOT NULL,
    first_name character varying NOT NULL,
    last_name character varying NOT NULL,
    password character varying NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_on timestamp without time zone DEFAULT now() NOT NULL,
    created_by character varying,
    updated_on timestamp without time zone DEFAULT now() NOT NULL,
    updated_by character varying
);


ALTER TABLE public.users OWNER TO aampere;

--
-- Name: vehicles; Type: TABLE; Schema: public; Owner: aampere
--

CREATE TABLE public.vehicles (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    brand character varying NOT NULL,
    model character varying NOT NULL,
    year integer NOT NULL,
    price numeric NOT NULL,
    range_km numeric NOT NULL,
    color character varying NOT NULL,
    condition character varying NOT NULL,
    "battery_capacity_kWh" numeric NOT NULL,
    "charging_speed_kW" numeric NOT NULL,
    seats integer NOT NULL,
    drivetrain character varying NOT NULL,
    location character varying NOT NULL,
    autopilot boolean DEFAULT false NOT NULL,
    kilometer_count integer NOT NULL,
    accidents boolean DEFAULT false NOT NULL,
    accidents_description character varying,
    images text NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_on timestamp without time zone DEFAULT now() NOT NULL,
    created_by character varying,
    updated_on timestamp without time zone DEFAULT now() NOT NULL,
    updated_by character varying
);


ALTER TABLE public.vehicles OWNER TO aampere;

--
-- Name: migrations id; Type: DEFAULT; Schema: public; Owner: aampere
--

ALTER TABLE ONLY public.migrations ALTER COLUMN id SET DEFAULT nextval('public.migrations_id_seq'::regclass);


--
-- Data for Name: migrations; Type: TABLE DATA; Schema: public; Owner: aampere
--

COPY public.migrations (id, "timestamp", name) FROM stdin;
1	1738892364859	Migration1738892364859
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: aampere
--

COPY public.users (id, username, first_name, last_name, password, is_active, created_on, created_by, updated_on, updated_by) FROM stdin;
b50f1fb0-6022-49c3-8aa3-d66919f26da7	username	firstName	lastName	$2b$10$PNvjlNCuKST.6FVoDxavzO7EtNPtt8UhjlX8WgWxdn5TfXq3Xzxqi	t	2025-02-07 01:40:16.146408	\N	2025-02-07 01:40:16.146408	\N
\.


--
-- Data for Name: vehicles; Type: TABLE DATA; Schema: public; Owner: aampere
--

COPY public.vehicles (id, brand, model, year, price, range_km, color, condition, "battery_capacity_kWh", "charging_speed_kW", seats, drivetrain, location, autopilot, kilometer_count, accidents, accidents_description, images, is_active, created_on, created_by, updated_on, updated_by) FROM stdin;
e573e767-6142-41af-89cb-d2518c8190bd	Tesla	Model S	2020	79999	610	Red	Used	100	250	5	AWD	Berlin	t	25000	t	\N	https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-01@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-02@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-03@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-04@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-05@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-06@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-07@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-08@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-09@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-10@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-11@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-12@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-13@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-14@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-15@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-16@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-17@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-18@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-19@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-20@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-21@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-22@2x.jpg	t	2025-02-07 01:41:42.766472	\N	2025-02-07 01:41:42.766472	\N
4f169d5f-b7ff-4d80-92b7-6881937cc186	Nissan	Leaf	2019	29999	270	White	New	40	50	5	FWD	München	f	0	f	\N	https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-01@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-02@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-03@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-04@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-05@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-06@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-07@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-08@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-09@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-10@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-11@2x.jpg	t	2025-02-07 01:41:42.787299	\N	2025-02-07 01:41:42.787299	\N
9a4d77dd-d36d-467b-aa9b-a964681792ea	BMW	i3	2021	45999	300	Black	New	42	50	4	RWD	Hamburg	f	500	f	\N	https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-01@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-02@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-03@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-04@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-05@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-06@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-07@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-08@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-09@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-10@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-11@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-12@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-13@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-14@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-15@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-16@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-17@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-18@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-19@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-20@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-21@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-22@2x.jpg	t	2025-02-07 01:41:42.804697	\N	2025-02-07 01:41:42.804697	\N
0b2a350b-a881-4b7f-be66-e71261791c2b	Audi	e-tron	2022	69999	400	Blue	New	95	150	5	AWD	Frankfurt am Main	t	0	f	\N	https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-01@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-02@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-03@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-04@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-05@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-06@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-07@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-08@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-09@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-10@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-11@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-12@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-13@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-14@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-15@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-16@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-17@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-18@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-19@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-20@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-21@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-22@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-23@2x.jpg	t	2025-02-07 01:41:42.820758	\N	2025-02-07 01:41:42.820758	\N
f47329b2-2e4c-4ed2-92e2-58d34e0bc198	Volkswagen	ID.3	2020	34999	420	Silver	New	58	100	5	RWD	Köln	f	100	f	\N	https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-01@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-02@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-03@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-04@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-05@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-06@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-07@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-08@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-09@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-10@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-11@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-12@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-13@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-14@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-15@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-16@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-17@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-18@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-19@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-20@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-21@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-22@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-23@2x.jpg	t	2025-02-07 01:41:42.836968	\N	2025-02-07 01:41:42.836968	\N
0f294201-f265-42ee-9e19-2ef311d0fdf2	Renault	Zoe	2018	19999	300	Grey	Used	41	22	5	FWD	Stuttgart	f	35000	t	\N	https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-01@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-02@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-03@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-04@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-05@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-06@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-07@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-08@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-09@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-10@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-11@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-12@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-13@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-14@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-15@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-16@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-17@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-18@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-19@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-20@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-21@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-22@2x.jpg	t	2025-02-07 01:41:42.853973	\N	2025-02-07 01:41:42.853973	\N
c53e7d93-cf52-421b-ba86-99b67df3b60a	Hyundai	Kona Electric	2021	37999	484	Blue	New	64	100	5	FWD	Düsseldorf	f	0	f	\N	https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-01@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-02@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-03@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-04@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-05@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-06@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-07@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-08@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-09@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-10@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-11@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-12@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-13@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-14@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-15@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-16@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-17@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-18@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-19@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-20@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-21@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-22@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-23@2x.jpg	t	2025-02-07 01:41:42.873812	\N	2025-02-07 01:41:42.873812	\N
348727ed-3519-47d8-9b09-a89c9ba41c47	Kia	e-Niro	2020	35999	455	White	New	64	77	5	FWD	Leipzig	f	200	f	\N	https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-01@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-02@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-03@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-04@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-05@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-06@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-07@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-08@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-09@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-10@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-11@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-12@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-13@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-14@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-15@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-16@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-17@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-18@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-19@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-20@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-21@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-22@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-23@2x.jpg	t	2025-02-07 01:41:42.895703	\N	2025-02-07 01:41:42.895703	\N
bbbb2923-d549-45a3-9a0a-40d6614984c9	Jaguar	I-PACE	2019	64999	470	Red	Used	90	100	5	AWD	München	f	15000	f	\N	https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-01@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-02@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-03@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-04@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-05@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-06@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-07@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-08@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-09@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-10@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-11@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-12@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-13@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-14@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-15@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-16@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-17@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-18@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-19@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-20@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-21@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-22@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-23@2x.jpg	t	2025-02-07 01:41:42.914029	\N	2025-02-07 01:41:42.914029	\N
966b7340-b91f-4941-b85e-aba392fa639b	Mercedes-Benz	EQC	2021	72999	417	Silver	New	80	110	5	AWD	Berlin	f	0	f	\N	https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-01@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-02@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-03@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-04@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-05@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-06@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-07@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-08@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-09@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-10@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-11@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-12@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-13@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-14@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-15@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-16@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-17@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-18@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-19@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-20@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-21@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-22@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-23@2x.jpg	t	2025-02-07 01:41:42.931189	\N	2025-02-07 01:41:42.931189	\N
aa721f7f-5deb-480f-8af0-8a4389e9c565	Tesla	Model 3	2021	49999	560	White	New	75	250	5	RWD	Berlin	t	0	f	\N	https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-01@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-02@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-03@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-04@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-05@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-06@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-07@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-08@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-09@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-10@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-11@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-12@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-13@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-14@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-15@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-16@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-17@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-18@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-19@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-20@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-21@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-22@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-23@2x.jpg	t	2025-02-07 01:41:42.951281	\N	2025-02-07 01:41:42.951281	\N
40fb9ea4-a126-4de7-8bfa-e5b715283aa3	Volkswagen	e-Golf	2019	27999	230	Blue	Used	35.8	40	5	FWD	Hamburg	f	15000	t	\N	https://ev-database.org/img/auto/BMW_i3_94Ah/BMW_i3_94Ah-01@2x.jpg,https://ev-database.org/img/auto/BMW_i3_94Ah/BMW_i3_94Ah-02@2x.jpg,https://ev-database.org/img/auto/BMW_i3_94Ah/BMW_i3_94Ah-03@2x.jpg,https://ev-database.org/img/auto/BMW_i3_94Ah/BMW_i3_94Ah-04@2x.jpg,https://ev-database.org/img/auto/BMW_i3_94Ah/BMW_i3_94Ah-05@2x.jpg,https://ev-database.org/img/auto/BMW_i3_94Ah/BMW_i3_94Ah-06@2x.jpg,https://ev-database.org/img/auto/BMW_i3_94Ah/BMW_i3_94Ah-07@2x.jpg,https://ev-database.org/img/auto/BMW_i3_94Ah/BMW_i3_94Ah-08@2x.jpg,https://ev-database.org/img/auto/BMW_i3_94Ah/BMW_i3_94Ah-09@2x.jpg,https://ev-database.org/img/auto/BMW_i3_94Ah/BMW_i3_94Ah-10@2x.jpg,https://ev-database.org/img/auto/BMW_i3_94Ah/BMW_i3_94Ah-11@2x.jpg,https://ev-database.org/img/auto/BMW_i3_94Ah/BMW_i3_94Ah-12@2x.jpg,https://ev-database.org/img/auto/BMW_i3_94Ah/BMW_i3_94Ah-13@2x.jpg,https://ev-database.org/img/auto/BMW_i3_94Ah/BMW_i3_94Ah-14@2x.jpg,https://ev-database.org/img/auto/BMW_i3_94Ah/BMW_i3_94Ah-15@2x.jpg,https://ev-database.org/img/auto/BMW_i3_94Ah/BMW_i3_94Ah-16@2x.jpg	t	2025-02-07 01:41:42.970115	\N	2025-02-07 01:41:42.970115	\N
40ce3e27-43b6-4b62-a365-d97d21299584	Peugeot	e-208	2020	30999	340	Yellow	New	50	100	5	FWD	Köln	f	0	f	\N	https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-01@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-02@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-03@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-04@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-05@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-06@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-07@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-08@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-09@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-10@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-11@2x.jpg	t	2025-02-07 01:41:42.98913	\N	2025-02-07 01:41:42.98913	\N
135c90fd-4844-455c-bddb-3a6a164985db	Opel	Corsa-e	2021	28999	330	Red	New	50	100	5	FWD	Stuttgart	f	0	f	\N	https://ev-database.org/img/auto/BMW_i3_94Ah/BMW_i3_94Ah-01@2x.jpg,https://ev-database.org/img/auto/BMW_i3_94Ah/BMW_i3_94Ah-02@2x.jpg,https://ev-database.org/img/auto/BMW_i3_94Ah/BMW_i3_94Ah-03@2x.jpg,https://ev-database.org/img/auto/BMW_i3_94Ah/BMW_i3_94Ah-04@2x.jpg,https://ev-database.org/img/auto/BMW_i3_94Ah/BMW_i3_94Ah-05@2x.jpg,https://ev-database.org/img/auto/BMW_i3_94Ah/BMW_i3_94Ah-06@2x.jpg,https://ev-database.org/img/auto/BMW_i3_94Ah/BMW_i3_94Ah-07@2x.jpg,https://ev-database.org/img/auto/BMW_i3_94Ah/BMW_i3_94Ah-08@2x.jpg,https://ev-database.org/img/auto/BMW_i3_94Ah/BMW_i3_94Ah-09@2x.jpg,https://ev-database.org/img/auto/BMW_i3_94Ah/BMW_i3_94Ah-10@2x.jpg,https://ev-database.org/img/auto/BMW_i3_94Ah/BMW_i3_94Ah-11@2x.jpg,https://ev-database.org/img/auto/BMW_i3_94Ah/BMW_i3_94Ah-12@2x.jpg,https://ev-database.org/img/auto/BMW_i3_94Ah/BMW_i3_94Ah-13@2x.jpg,https://ev-database.org/img/auto/BMW_i3_94Ah/BMW_i3_94Ah-14@2x.jpg,https://ev-database.org/img/auto/BMW_i3_94Ah/BMW_i3_94Ah-15@2x.jpg,https://ev-database.org/img/auto/BMW_i3_94Ah/BMW_i3_94Ah-16@2x.jpg	t	2025-02-07 01:41:43.011543	\N	2025-02-07 01:41:43.011543	\N
0cc3e814-2f00-42c3-951e-168fddfac89e	Honda	e	2021	34999	220	Grey	New	35.5	100	4	RWD	Düsseldorf	f	0	f	\N	https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-01@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-02@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-03@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-04@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-05@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-06@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-07@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-08@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-09@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-10@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-11@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-12@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-13@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-14@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-15@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-16@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-17@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-18@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-19@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-20@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-21@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-22@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-23@2x.jpg	t	2025-02-07 01:41:43.031605	\N	2025-02-07 01:41:43.031605	\N
76a74032-4ca0-48f2-a748-33e48ea45057	Porsche	Taycan	2020	104999	450	White	Used	93.4	270	4	AWD	Frankfurt am Main	f	5000	f	\N	https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-01@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-02@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-03@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-04@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-05@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-06@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-07@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-08@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-09@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-10@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-11@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-12@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-13@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-14@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-15@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-16@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-17@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-18@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-19@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-20@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-21@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-22@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-23@2x.jpg	t	2025-02-07 01:41:43.050495	\N	2025-02-07 01:41:43.050495	\N
5fd6033d-eb2e-4f6e-9913-c81622d22fb8	Tesla	Model X	2019	89999	507	Black	Used	100	250	7	AWD	Berlin	t	30000	t	\N	https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-01@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-02@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-03@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-04@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-05@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-06@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-07@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-08@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-09@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-10@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-11@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-12@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-13@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-14@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-15@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-16@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-17@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-18@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-19@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-20@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-21@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-22@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-23@2x.jpg	t	2025-02-07 01:41:43.067852	\N	2025-02-07 01:41:43.067852	\N
a9c164bc-d2f4-4441-9c79-55ceb067253d	Fiat	500e	2020	24999	320	Green	New	42	85	4	FWD	München	f	0	f	\N	https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-01@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-02@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-03@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-04@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-05@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-06@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-07@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-08@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-09@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-10@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-11@2x.jpg	t	2025-02-07 01:41:43.084134	\N	2025-02-07 01:41:43.084134	\N
ba6decff-bdc2-437d-ab50-722864b308b3	Mazda	MX-30	2021	26999	200	Silver	New	35.5	50	5	FWD	Köln	f	0	f	\N	https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-01@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-02@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-03@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-04@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-05@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-06@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-07@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-08@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-09@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-10@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-11@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-12@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-13@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-14@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-15@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-16@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-17@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-18@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-19@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-20@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-21@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-22@2x.jpg	t	2025-02-07 01:41:43.101375	\N	2025-02-07 01:41:43.101375	\N
63174702-e681-477d-bc8d-9cc7f8cae206	Mini	Cooper SE	2021	31999	235	Yellow	New	32.6	50	4	FWD	Hamburg	f	0	f	\N	https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-01@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-02@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-03@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-04@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-05@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-06@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-07@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-08@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-09@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-10@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-11@2x.jpg	t	2025-02-07 01:41:43.117044	\N	2025-02-07 01:41:43.117044	\N
4f9d49db-74dc-4939-865e-4e911036d435	Tesla	Model Y	2021	59999	505	Blue	New	75	250	5	AWD	Berlin	t	0	f	\N	https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-01@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-02@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-03@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-04@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-05@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-06@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-07@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-08@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-09@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-10@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-11@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-12@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-13@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-14@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-15@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-16@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-17@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-18@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-19@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-20@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-21@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-22@2x.jpg	t	2025-02-07 01:41:43.13466	\N	2025-02-07 01:41:43.13466	\N
22a687f0-210d-424d-8838-6edab0d79495	Ford	Mustang Mach-E	2021	53999	480	Red	New	88	150	5	RWD	Frankfurt am Main	f	0	f	\N	https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-01@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-02@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-03@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-04@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-05@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-06@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-07@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-08@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-09@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-10@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-11@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-12@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-13@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-14@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-15@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-16@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-17@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-18@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-19@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-20@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-21@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-22@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-23@2x.jpg	t	2025-02-07 01:41:43.154194	\N	2025-02-07 01:41:43.154194	\N
dac58d6d-f0ee-4154-9e14-cb6dc33f36bb	Skoda	Enyaq iV	2021	39999	510	Grey	New	77	125	5	RWD	Leipzig	f	0	f	\N	https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-01@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-02@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-03@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-04@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-05@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-06@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-07@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-08@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-09@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-10@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-11@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-12@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-13@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-14@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-15@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-16@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-17@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-18@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-19@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-20@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-21@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-22@2x.jpg	t	2025-02-07 01:41:43.183151	\N	2025-02-07 01:41:43.183151	\N
04b154ca-f029-4799-a1b1-85f75dc2996b	Citroën	ë-C4	2021	34999	350	Blue	New	50	100	5	FWD	Düsseldorf	f	0	f	\N	https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-01@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-02@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-03@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-04@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-05@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-06@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-07@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-08@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-09@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-10@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-11@2x.jpg	t	2025-02-07 01:41:43.204482	\N	2025-02-07 01:41:43.204482	\N
eb42d67c-e387-4474-87b9-c2f2f0d36dc7	Renault	Twingo Z.E.	2020	21999	190	White	New	22	22	4	RWD	Stuttgart	f	0	f	\N	https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-01@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-02@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-03@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-04@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-05@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-06@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-07@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-08@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-09@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-10@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-11@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-12@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-13@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-14@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-15@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-16@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-17@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-18@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-19@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-20@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-21@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-22@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-23@2x.jpg	t	2025-02-07 01:41:43.230996	\N	2025-02-07 01:41:43.230996	\N
656533ba-cbd0-4c5e-b966-0e5cf45e2849	Volvo	XC40 Recharge	2021	58999	400	Black	New	78	150	5	AWD	München	f	0	f	\N	https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-01@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-02@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-03@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-04@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-05@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-06@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-07@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-08@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-09@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-10@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-11@2x.jpg	t	2025-02-07 01:41:43.252109	\N	2025-02-07 01:41:43.252109	\N
d6f44e0a-f083-4e32-8bc6-aff41eb10bb4	Audi	e-tron GT	2021	99999	488	Silver	New	93.4	270	4	AWD	Frankfurt am Main	f	0	f	\N	https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-01@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-02@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-03@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-04@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-05@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-06@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-07@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-08@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-09@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-10@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-11@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-12@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-13@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-14@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-15@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-16@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-17@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-18@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-19@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-20@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-21@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-22@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-23@2x.jpg	t	2025-02-07 01:41:43.278704	\N	2025-02-07 01:41:43.278704	\N
42094279-d831-426e-ba21-4e9365dc897b	BMW	iX3	2021	67999	460	White	New	80	150	5	RWD	Leipzig	f	0	f	\N	https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-01@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-02@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-03@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-04@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-05@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-06@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-07@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-08@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-09@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-10@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-11@2x.jpg	t	2025-02-07 01:41:43.301476	\N	2025-02-07 01:41:43.301476	\N
52e9a5ae-2dcf-447c-932e-f3f7f6da91c3	Porsche	Taycan Cross Turismo	2021	109999	456	Blue	New	93.4	270	5	AWD	Frankfurt am Main	f	0	f	\N	https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-01@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-02@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-03@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-04@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-05@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-06@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-07@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-08@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-09@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-10@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-11@2x.jpg	t	2025-02-07 01:41:43.714016	\N	2025-02-07 01:41:43.714016	\N
6cc50b17-65aa-4ad2-9686-7579f7cbda72	Mercedes-Benz	EQA	2021	47999	426	Blue	New	66.5	100	5	FWD	Düsseldorf	f	0	f	\N	https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-01@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-02@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-03@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-04@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-05@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-06@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-07@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-08@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-09@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-10@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-11@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-12@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-13@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-14@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-15@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-16@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-17@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-18@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-19@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-20@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-21@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-22@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-23@2x.jpg	t	2025-02-07 01:41:43.32463	\N	2025-02-07 01:41:43.32463	\N
2f7af9f5-068b-4e08-af49-d84e854ef7d2	Hyundai	Ioniq Electric	2020	32999	311	Silver	Used	38.3	100	5	FWD	Köln	f	10000	f	\N	https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-01@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-02@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-03@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-04@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-05@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-06@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-07@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-08@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-09@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-10@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-11@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-12@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-13@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-14@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-15@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-16@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-17@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-18@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-19@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-20@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-21@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-22@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-23@2x.jpg	t	2025-02-07 01:41:43.349294	\N	2025-02-07 01:41:43.349294	\N
de5275bf-48f4-41f7-9d7e-1a482595b67f	Kia	Soul EV	2020	36999	452	Red	Used	64	100	5	FWD	München	f	5000	t	\N	https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-01@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-02@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-03@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-04@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-05@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-06@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-07@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-08@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-09@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-10@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-11@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-12@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-13@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-14@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-15@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-16@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-17@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-18@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-19@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-20@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-21@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-22@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-23@2x.jpg	t	2025-02-07 01:41:43.373703	\N	2025-02-07 01:41:43.373703	\N
09ac1fab-575e-4d45-8bb7-805483f2161c	Polestar	2	2021	59999	470	White	New	78	150	5	AWD	Hamburg	f	0	f	\N	https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-01@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-02@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-03@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-04@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-05@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-06@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-07@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-08@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-09@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-10@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-11@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-12@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-13@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-14@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-15@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-16@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-17@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-18@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-19@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-20@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-21@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-22@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-23@2x.jpg	t	2025-02-07 01:41:43.397267	\N	2025-02-07 01:41:43.397267	\N
dac21576-dc60-4c70-9a3d-6b0628d57795	Nissan	Ariya	2021	47999	500	Gold	New	87	130	5	FWD	Leipzig	f	0	f	\N	https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-01@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-02@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-03@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-04@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-05@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-06@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-07@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-08@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-09@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-10@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-11@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-12@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-13@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-14@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-15@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-16@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-17@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-18@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-19@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-20@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-21@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-22@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-23@2x.jpg	t	2025-02-07 01:41:43.41552	\N	2025-02-07 01:41:43.41552	\N
eb1afdf0-a2d9-4d19-a6a1-a28d3393805d	Tesla	Model 3	2022	51999	580	Red	New	82	250	5	AWD	Berlin	t	0	f	\N	https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-01@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-02@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-03@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-04@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-05@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-06@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-07@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-08@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-09@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-10@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-11@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-12@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-13@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-14@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-15@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-16@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-17@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-18@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-19@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-20@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-21@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-22@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-23@2x.jpg	t	2025-02-07 01:41:43.431435	\N	2025-02-07 01:41:43.431435	\N
4b9b75c2-33fe-4240-adc4-3bd59942a88c	Renault	Megane E-Tech	2021	35999	470	Blue	New	60	130	5	FWD	Stuttgart	f	0	f	\N	https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-01@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-02@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-03@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-04@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-05@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-06@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-07@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-08@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-09@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-10@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-11@2x.jpg	t	2025-02-07 01:41:43.448294	\N	2025-02-07 01:41:43.448294	\N
40419987-1688-41dd-b2aa-7f32569bf14b	Volkswagen	ID.4	2021	44999	520	White	New	77	125	5	RWD	Hamburg	f	0	f	\N	https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-01@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-02@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-03@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-04@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-05@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-06@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-07@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-08@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-09@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-10@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-11@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-12@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-13@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-14@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-15@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-16@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-17@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-18@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-19@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-20@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-21@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-22@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-23@2x.jpg	t	2025-02-07 01:41:43.465256	\N	2025-02-07 01:41:43.465256	\N
1f354251-82e7-4599-b771-dd3d297e5ea0	Audi	Q4 e-tron	2021	49999	520	Black	New	77	125	5	AWD	Frankfurt am Main	f	0	f	\N	https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-01@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-02@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-03@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-04@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-05@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-06@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-07@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-08@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-09@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-10@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-11@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-12@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-13@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-14@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-15@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-16@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-17@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-18@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-19@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-20@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-21@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-22@2x.jpg	t	2025-02-07 01:41:43.484109	\N	2025-02-07 01:41:43.484109	\N
4c9cebd8-d80c-4eb3-b396-a6fc17172127	Opel	Mokka-e	2021	32999	322	Green	New	50	100	5	FWD	Düsseldorf	f	0	f	\N	https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-01@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-02@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-03@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-04@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-05@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-06@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-07@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-08@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-09@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-10@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-11@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-12@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-13@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-14@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-15@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-16@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-17@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-18@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-19@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-20@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-21@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-22@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-23@2x.jpg	t	2025-02-07 01:41:43.500371	\N	2025-02-07 01:41:43.500371	\N
10965f9c-2a59-4daa-9309-69bc1dc56e59	BMW	i4	2022	56999	590	Blue	New	83.9	200	5	RWD	München	f	0	f	\N	https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-01@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-02@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-03@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-04@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-05@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-06@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-07@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-08@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-09@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-10@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-11@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-12@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-13@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-14@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-15@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-16@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-17@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-18@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-19@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-20@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-21@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-22@2x.jpg	t	2025-02-07 01:41:43.519811	\N	2025-02-07 01:41:43.519811	\N
10b6e091-9ed8-473b-82e7-51fb94eba045	Mercedes-Benz	EQB	2021	52999	419	Silver	New	66.5	100	7	AWD	Stuttgart	f	0	f	\N	https://ev-database.org/img/auto/BMW_i3_94Ah/BMW_i3_94Ah-01@2x.jpg,https://ev-database.org/img/auto/BMW_i3_94Ah/BMW_i3_94Ah-02@2x.jpg,https://ev-database.org/img/auto/BMW_i3_94Ah/BMW_i3_94Ah-03@2x.jpg,https://ev-database.org/img/auto/BMW_i3_94Ah/BMW_i3_94Ah-04@2x.jpg,https://ev-database.org/img/auto/BMW_i3_94Ah/BMW_i3_94Ah-05@2x.jpg,https://ev-database.org/img/auto/BMW_i3_94Ah/BMW_i3_94Ah-06@2x.jpg,https://ev-database.org/img/auto/BMW_i3_94Ah/BMW_i3_94Ah-07@2x.jpg,https://ev-database.org/img/auto/BMW_i3_94Ah/BMW_i3_94Ah-08@2x.jpg,https://ev-database.org/img/auto/BMW_i3_94Ah/BMW_i3_94Ah-09@2x.jpg,https://ev-database.org/img/auto/BMW_i3_94Ah/BMW_i3_94Ah-10@2x.jpg,https://ev-database.org/img/auto/BMW_i3_94Ah/BMW_i3_94Ah-11@2x.jpg,https://ev-database.org/img/auto/BMW_i3_94Ah/BMW_i3_94Ah-12@2x.jpg,https://ev-database.org/img/auto/BMW_i3_94Ah/BMW_i3_94Ah-13@2x.jpg,https://ev-database.org/img/auto/BMW_i3_94Ah/BMW_i3_94Ah-14@2x.jpg,https://ev-database.org/img/auto/BMW_i3_94Ah/BMW_i3_94Ah-15@2x.jpg,https://ev-database.org/img/auto/BMW_i3_94Ah/BMW_i3_94Ah-16@2x.jpg	t	2025-02-07 01:41:43.547798	\N	2025-02-07 01:41:43.547798	\N
ab3a5134-52e7-418f-bc61-587b5be2679f	Peugeot	e-2008	2021	37999	320	Orange	New	50	100	5	FWD	Leipzig	f	0	f	\N	https://ev-database.org/img/auto/BMW_i3_94Ah/BMW_i3_94Ah-01@2x.jpg,https://ev-database.org/img/auto/BMW_i3_94Ah/BMW_i3_94Ah-02@2x.jpg,https://ev-database.org/img/auto/BMW_i3_94Ah/BMW_i3_94Ah-03@2x.jpg,https://ev-database.org/img/auto/BMW_i3_94Ah/BMW_i3_94Ah-04@2x.jpg,https://ev-database.org/img/auto/BMW_i3_94Ah/BMW_i3_94Ah-05@2x.jpg,https://ev-database.org/img/auto/BMW_i3_94Ah/BMW_i3_94Ah-06@2x.jpg,https://ev-database.org/img/auto/BMW_i3_94Ah/BMW_i3_94Ah-07@2x.jpg,https://ev-database.org/img/auto/BMW_i3_94Ah/BMW_i3_94Ah-08@2x.jpg,https://ev-database.org/img/auto/BMW_i3_94Ah/BMW_i3_94Ah-09@2x.jpg,https://ev-database.org/img/auto/BMW_i3_94Ah/BMW_i3_94Ah-10@2x.jpg,https://ev-database.org/img/auto/BMW_i3_94Ah/BMW_i3_94Ah-11@2x.jpg,https://ev-database.org/img/auto/BMW_i3_94Ah/BMW_i3_94Ah-12@2x.jpg,https://ev-database.org/img/auto/BMW_i3_94Ah/BMW_i3_94Ah-13@2x.jpg,https://ev-database.org/img/auto/BMW_i3_94Ah/BMW_i3_94Ah-14@2x.jpg,https://ev-database.org/img/auto/BMW_i3_94Ah/BMW_i3_94Ah-15@2x.jpg,https://ev-database.org/img/auto/BMW_i3_94Ah/BMW_i3_94Ah-16@2x.jpg	t	2025-02-07 01:41:43.567661	\N	2025-02-07 01:41:43.567661	\N
e84e1ddc-91dc-4160-9932-7f5ff4a09744	Fiat	500e 3+1	2021	26999	320	Pink	New	42	85	4	FWD	Berlin	f	0	f	\N	https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-01@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-02@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-03@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-04@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-05@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-06@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-07@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-08@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-09@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-10@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-11@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-12@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-13@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-14@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-15@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-16@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-17@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-18@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-19@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-20@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-21@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-22@2x.jpg,https://ev-database.org/img/auto/Tesla_Model_S/Tesla_Model_S-23@2x.jpg	t	2025-02-07 01:41:43.587995	\N	2025-02-07 01:41:43.587995	\N
0ef926e9-2d79-4d66-b782-bd4781814530	Mazda	MX-30	2020	25999	200	White	Used	35.5	50	5	FWD	München	f	8000	t	\N	https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-01@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-02@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-03@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-04@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-05@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-06@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-07@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-08@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-09@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-10@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-11@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-12@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-13@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-14@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-15@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-16@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-17@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-18@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-19@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-20@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-21@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-22@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-23@2x.jpg	t	2025-02-07 01:41:43.609984	\N	2025-02-07 01:41:43.609984	\N
a4138b38-cd56-47ae-b47c-a2471989bb45	Honda	e Advance	2021	36999	210	Yellow	New	35.5	100	4	RWD	Hamburg	f	0	f	\N	https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-01@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-02@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-03@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-04@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-05@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-06@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-07@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-08@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-09@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-10@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-11@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-12@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-13@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-14@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-15@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-16@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-17@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-18@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-19@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-20@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-21@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-22@2x.jpg,https://ev-database.org/img/auto/Ford_Mustang_Mach-E/Ford_Mustang_Mach-E-23@2x.jpg	t	2025-02-07 01:41:43.63116	\N	2025-02-07 01:41:43.63116	\N
be7690e3-8224-45f6-842d-a0646d59b179	Nissan	Leaf e+	2020	34999	385	Silver	Used	62	100	5	FWD	Stuttgart	f	12000	f	\N	https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-01@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-02@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-03@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-04@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-05@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-06@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-07@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-08@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-09@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-10@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-11@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-12@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-13@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-14@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-15@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-16@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-17@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-18@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-19@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-20@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-21@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-22@2x.jpg	t	2025-02-07 01:41:43.652096	\N	2025-02-07 01:41:43.652096	\N
04f397c4-7072-4fc8-a64e-91af53db9368	Kia	EV6	2021	45999	528	Red	New	77.4	220	5	RWD	Düsseldorf	f	0	f	\N	https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-01@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-02@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-03@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-04@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-05@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-06@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-07@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-08@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-09@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-10@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-11@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-12@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-13@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-14@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-15@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-16@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-17@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-18@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-19@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-20@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-21@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-22@2x.jpg	t	2025-02-07 01:41:43.675884	\N	2025-02-07 01:41:43.675884	\N
4f947cc2-a31e-4c75-9f60-2e56d21ee7ff	Hyundai	Ioniq 5	2021	46999	481	Grey	New	77.4	220	5	AWD	Leipzig	f	0	f	\N	https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-01@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-02@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-03@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-04@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-05@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-06@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-07@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-08@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-09@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-10@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-11@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-12@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-13@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-14@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-15@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-16@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-17@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-18@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-19@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-20@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-21@2x.jpg,https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-22@2x.jpg	t	2025-02-07 01:41:43.696673	\N	2025-02-07 01:41:43.696673	\N
2aa11661-0005-486b-b927-f61e8b777b5f	Tesla	Model S Plaid	2021	129999	628	Black	New	100	250	5	AWD	Berlin	t	0	f	\N	https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-01@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-02@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-03@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-04@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-05@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-06@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-07@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-08@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-09@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-10@2x.jpg,https://ev-database.org/img/auto/Porsche_Taycan/Porsche_Taycan-11@2x.jpg	t	2025-02-07 01:41:43.730404	\N	2025-02-07 01:41:43.730404	\N
\.


--
-- Name: migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: aampere
--

SELECT pg_catalog.setval('public.migrations_id_seq', 1, true);


--
-- Name: vehicles PK_18d8646b59304dce4af3a9e35b6; Type: CONSTRAINT; Schema: public; Owner: aampere
--

ALTER TABLE ONLY public.vehicles
    ADD CONSTRAINT "PK_18d8646b59304dce4af3a9e35b6" PRIMARY KEY (id);


--
-- Name: migrations PK_8c82d7f526340ab734260ea46be; Type: CONSTRAINT; Schema: public; Owner: aampere
--

ALTER TABLE ONLY public.migrations
    ADD CONSTRAINT "PK_8c82d7f526340ab734260ea46be" PRIMARY KEY (id);


--
-- Name: users PK_a3ffb1c0c8416b9fc6f907b7433; Type: CONSTRAINT; Schema: public; Owner: aampere
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY (id);


--
-- Name: users UQ_fe0bb3f6520ee0469504521e710; Type: CONSTRAINT; Schema: public; Owner: aampere
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE (username);


--
-- PostgreSQL database dump complete
--

--
-- Database "postgres" dump
--

\connect postgres

--
-- PostgreSQL database dump
--

-- Dumped from database version 17.2 (Debian 17.2-1.pgdg120+1)
-- Dumped by pg_dump version 17.2 (Debian 17.2-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- PostgreSQL database dump complete
--

--
-- PostgreSQL database cluster dump complete
--

